site_name: Dev Docs
site_description: Documentacion para desarrolladores
site_url: https://ojoshuacg.github.io/dev-docs/

repo_url: https://github.com/OJoshuaCG/dev-docs
edit_uri: edit/main/dev-docs/docs

# Setting navigation titles and files
nav:
  - Inicio: index.md
  - git:
      - Primeros Pasos: git/index.md
      - Guardando cambios: git/handling-changes.md
      - Commit: git/commit.md
      - Modificando proyecto: git/undoing-project.md
      - Branch: git/branch.md
      # - Repositorios remotos: git/remote-repositories.md
      # - gitignore: git/gitignore.md
      # -

  - sql:
      - Usuarios: sql/users.md
      - DML: sql/dml.md
      - DDL: sql/ddl.md
      - DCL: sql/dcl.md
  # - Github
  # - Github CLI
  # - Github Actions
  - Docker:
      - Instalacion: docker/index.md
      - Comandos: docker/command-line.md
      - Base de datos: docker/databases-images.md

# CSS file custom
extra_css:
  - stylesheets/custom.css

# Setting colorscheme for custom theme
theme:
  # Setting theme, in this case: mkdocs-material
  # https://squidfunk.github.io/mkdocs-material/
  name: material

  # nav_style: dark

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: custom

  # feature's code scopes
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

# Disable search engine
plugins: []

# Some markdown utilities
markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
